//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxxyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculos
    {
        public int id { get; set; }
        public int idProprietario { get; set; }
        public string placa { get; set; }
        public string renavam { get; set; }
        public string cpf { get; set; }
        public bool bloqueado { get; set; }
    }
}
